lh3/minimap2

- main.c
Reading the target from an index file causes a segmentation fault. This happens when trying to compare kmer and minimizer sizes in the index with those set on the command line the second time through an infinite loop. The fix is just to check that mi exists before checking the kmers and minimizers are equal.
> Fixed segfault caused when reading from index file

- python/mappy.pyx
See issue #53. Fixes sequences name, sequence and quality strings for Python3, whilst maintaining support for Python2.
Tested on Python 2.7.13 and Python 3.5.3, and each give identical results.
> Bug fix with byte strings in Python3

- python/mappy.pyx
Small bug in accessing `.strand` attribute of `Alignment`.
> Fix typo in strand property

- Makefile
- README.md
- sse2neon/emmintrin.h
A workaround to get minimap2 working on ARM processors using their NEON SIMD instructions.
- The headers that convert SSE to NEON are in sse2neon/emmintrin.h
- Some options were added to the makefile
- can be compiled for ARM with make arm_neon=1
- tested on Odroid XU4 and Raspberry Pi 3
> minimap2 on ARM processors 

- align.c
Fix the logic that calculates the number of CIGAR entries when
match "M" entries are expanded into "=" and "X".  The number
of entries depends not on the number of mismatches but rather
on the number of transitions between "=" to "X".
A test case that segfaults with the prior implementation is available
at https://gist.github.com/amwenger/b1e56ce4d9895d8f0c13707b6916800b.
minimap2 --eqx -a eqxref.fa eqxread.fa 1>/dev/null
cc: @armintoepfer
> Fix CIGAR reallocation with --eqx

- python/mappy.pyx
This is quite useful to me when aligning assembled ends of large inserts. The fist commit exposes this parameter in the Aligner class, so you can set this instance-wide. The second commit allows changing the max size per alignment, which I find useful as often I know the fragment size that I'm expecting for a particular set of assembled ends.
> Expose max_frag_len parameter at class level and per-alignment level

- index.c
- minimap.h
- This PR puts signatures `mm_idx_load()`, `mm_idx_dump()` and `mm_idx_is_idx()` in `minimap.h`
- The first commit prevents calling `strlen()` on null reference names in `mm_idx_dump`.
I am using `minimap2` from C++ and need explicit API for storing and loading an already created index. 
- Saving via the public API is currently impossible since `mm_idx_dump` is not exposed
- For loading one can get by with `mm_idx_reader_read` but I do not see a downside of exposing `mm_idx_load` which indicates intent much more clearly.
- The detection function `mm_idx_is_idx` is also nice to have for anyone using minimap2 as a library
Saving and loading works as expected with small testing references as well as hg19
> Expose index i/o functions in public API

- options.c
`-u b` implies `--splice` but `-u f` or `-u r` don't.
I don't know if it's a bug or a feature.
It went unnoticed because most people use `-x splice` anyway.
> --splice should be implied by -u f or -u r

- python/cmappy.h
Python threading does not generally allow multiple threads running parallel unless the global interpreter lock is explicitly released. With this patch, `Aligner.map` permits other Python threads running during its job. This would be quite useful when using asynchronous scheduling with `concurrent.futures.ThreadPoolExecutor` or using the other computationally expensive tasks like `numpy` or `sklearn` together with `mappy`.
> Release the GIL to allow the native Python threading.

- index.c
Hello, I have made a small change to the mm_idx_is_idx function so that it works correctly on Windows when using large index files.
When testing with index files in the order of gigabytes in size, we discovered that lseek does not return correct results for these very large files when compiled under MSVC.  Microsoft recommend _lseek and _lseeki64 instead:
https://docs.microsoft.com/en-gb/cpp/c-runtime-library/reference/lseek
Also "off_t" is defined as "long" in MSVC, which is only 4 bytes, so this also caused issues with indices over about 2GB.
Thanks :)
> Fixed mm_idx_is_idx to return the correct result on Windows.

- format.c
Don't compute `tlen` when either `r` or `r_next` indicates unmapped. Fixes #365.
(Compiled, but I have not rigorously tested this.)
> SAM TLEN should be 0 when either read is unmapped

- main.c
- map.c
- misc.c
- splitidx.c
Add the underlying operating system error (usually "No such file" or "No space left on device" respectively, but highly informative when it is not) to these error messages.
Provides more information in cases like #452.
> Add errno to file opening failure and I/O error messages

- main.c
Added `splice:hq` to `--help` output
Because that preset uses a colon `:` I changed the separator to hypen `-` too:
```
Preset:
-x STR       preset (always applied before other options; see minimap2.1 for details) []
- map-pb/map-ont - PacBio/Nanopore vs reference mapping
- ava-pb/ava-ont - PacBio/Nanopore read overlap
- asm5/asm10/asm20 - asm-to-ref mapping, for ~0.1/1/5% sequence divergence
- splice/splice:hq - long-read/Pacbio-CCS spliced alignment
- sr - genomic short-read mapping
```
> Add splice:hq to --help

- kseq.h
This is for compatibility with kstring_t in htslib.
> change kstring_t integer storage size

- kseq.h
- mmpriv.h
In my previous PR, I missed a second definition of kstring_t in mmpriv.h. This PR removes this definition and includes `kseq.h` instead. Sorry for missing this originally.
> remove kstring_t definition in mmpriv

- .travis.yml
Travis CI has [multiple CPU feature](https://docs.travis-ci.com/user/multi-cpu-architectures/) now.
Here is [the CI result](https://travis-ci.org/github/junaruga/minimap2/builds/674330400) on my forked repository.
You can also use `arch: ppc64le` and `arch: s390x` syntax when you want to use it.
> travis: added arm64 test.

- .gitmodules
- Makefile
- README.md
- ksw2_extd2_sse.c
- ksw2_exts2_sse.c
- ksw2_extz2_sse.c
- ksw2_ll_sse.c
Substituted sse2neon by SIMDe library to convert SSE2 to ARM Neon.
Added option to build non-SIMD version of minimap2 using SIMDe.
SIMDe is added as a git submodule.
> sse2neon -> SIMDe and added non-SIMD version

- align.c
Ensure that we never try to access uninitialized r->p, fixes https://github.com/lh3/minimap2/issues/622
> Initialize r->p if ez->zdropped

- setup.py
This should make cython installation a bit more robust and allows python3.9 support (on my machine at least).
Resolves #719
> Convert python install from build_ext to setuptools setup_requires.

- python/README.rst
Thanks for sharing minimap2. Here's a little fix.
> Typo fix in Python README.

- align.c
- example.c
- format.c
- ksw2.h
- minimap.h
- misc/paftools.js
- python/mappy.pyx
This PR has two commits that regularise the CIGAR operator handling:
1. Adds a `MM_CIGAR_STR` macro to _minimap.h_ and uses it throughout the C code instead of abbreviated strings like `"MIDN"`, and uses the full `"MIDNSHP=X"` string in the JavaScript REs and in the Cython code. #573 is an example of the incomplete operator list causing problems in the Cython code, and the C changes prevent any such problems there.
2. Creates `#define MM_CIGAR_MATCH 0` etc constants for the CIGAR operator values so that the C code involving CIGAR operators is more self-documenting, instead of needing comments saying what the `0`, `1`, `2`, etc constants are.
The first commit is a bug fix, especially for _mappy.pyx_ which may encounter data that has not come straight out of minimap. The second commit you …
> Use the full "MIDNSHP=X" list of CIGAR operators and use a named constant for each CIGAR operator

- Makefile.simde
I believe this fixes issues with compiling with Makefile.simde as there are missing targets
> missing target object files from Makefile.simde to fix issue #779

- main.c
Currently, even if the -I parameter is set, minimap2 seems to use up all the memory required to read in the entire genome file when building an index. I think that a memory leak was introduced from the `continue` statement at main.c:409 which prevented the `mm_idx_destroy` function from being called.
> Cleanup memory when creating index

- main.c
- minimap.h
Move `MM_VERSION` to minimap.h so it can be used by any application _(i.e https://github.com/lh3/minimap2/issues/1030)_ that is linking `libminimap2` and not building `minimap2`.
> move MM_VERSION to minimap.h

- ksw2_extd2_sse.c
- ksw2_exts2_sse.c
- ksw2_extz2_sse.c
Fixes the final update of the `mte_q` variable in the `ez` struct when computing the maximum without approximation in all the different aligners.
> Fixed alignment result final update when computing the exact max value

- python/mappy.pyx
mappy creates a CIGAR string by default (`-c` flag) and so is incompatible with indexes that are created using the `--idx-no-seq` flag.
The previous implementation of mappy did not check for the `MM_I_NO_SEQ` flag and would seg fault when attempting to map a read or retrieve a reference sequence from the index. This patch adds a check to both `mappy.Aligner.seq` and `mappy.Aligner.map` and returns `None` if there is no index sequences. I've chose `None` as this is inline with the behaviour of mappy for reads that do not align/retrieving sequences that aren't in the index, however it might be better to raise an exception so that this error is distinct and can be communicated to the caller.
closes #1007
> mappy check index flags before mapping

- README.md
- align.c
- main.c
- minimap.h
- options.c
Implements general purpose transition-aware alignment scoring, and configuration presets for alignment of ICLR to reference sequence contigs
> Illumina Complete Long Read presets

- index.c
If the allocated region is 0 bytes then it's unsafe to dereference it.
Fixes #1147.
> Avoid NULL pointer dereference

- python/cmappy.pxd
Hi!
I have noticed that the `mm_mapopt_t` structure in Mappy's `cmappy.pxd` is missing the recently added variable `transition`. This variable was introduced at #1069. 
Thank you.
> Fix mm_mapopt_t in Mappy

- format.c
The existing logic checked for is_MD == 1, but
the function is called with a bitwise operator check which does not evaluate to 1.
> Fix MD generation check in SAM writing

- python/cmappy.h
- python/cmappy.pxd
- python/mappy.pyx
This adds the (optional) ability to pass the read
name to the mappy `map` method.  Without the
read name, the call to `map` can sometimes give
different output than the command line version
of `minimap2` because of the way minimap uses
the hash of the read name to break ties in ordering hits.  
This can affect which / if certain supplementary alignments 
are generated, and even which / if non-primary alignments 
are generated.
> Allow passing read name to mappy

- misc/README.md
Was using `paftools.js` to convert a file and tripped up on this when reading the docs--it's clarified later on but the "Getting Started" section has a mistake.
> Fix error in paftools README.md

- python/mappy.pyx
Hi Heng,
as discussed at IGGSy, this PR exposes the `sc_ambi` and `max_gaplen` parameters already exposed on the CLI interface in the cython/mappy interface as well.
Same as other options in the mappy interface, they're set after initializing the preset and can overwrite it.
We're using this to align sequences in which we've inserted spacers that we do not want to align – not sure how common that use case is, but other people might also want to set these parameters for other reasons.
Best,
Leon
> Add `sc_ambi` and `max_chain_skip` parameters to `mappy.pyx`

- python/mappy.pyx
> fix error in mappy when dealing MD or CS tag of R2
